name: Starts unit-test on pull-request to dev

on:
  pull_request:
    branches:
      - dev

jobs:
  unit-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify your desired Python version

    - name: Install Dependencies
      run: |
        python -m pip install -r dev-requirements.txt

    - name: Run Unit Tests
      run: |
        pytest tests/ --cov src --cov-report term-missing --exitfirst --cov-fail-under=50

